name: Cloudflare Cleanup

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every week on Sunday at 00:00 UTC
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: read

jobs:
  clean:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [one-among-us, our-data]

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Clean Cloudflare Deployments (${{ matrix.project }})
        run: yarn cloudflare_clean
        env:
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CF_PAGES_PROJECT_NAME: ${{ matrix.project }}
